Repository CHTC/chtc-bot, pull requests merged in 2020-05, with the labels that each got.

#34 Revise /classad_eval
  tests/commands/test_classad_eval.py
  web/commands/classad_eval.py
Labels: enhancement, slash-commands

#37 (#33) Implement RSS feed reader using AWS Lambda function
  rss/.gitignore
  rss/README.md
  rss/deploy.sh
  rss/lambda/lambda.py
  rss/lambda/requirements.txt
  rss/template.yaml
Labels: enhancement, lambdas

#32 Forgetful storage refactoring
  tests/utils/test_forgetful_dict.py
  web/commands/scrapers.py
  web/utils.py
Labels: enhancement
